#CLAIM
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: system:default/vnncld-idp-dev-db
spec:
  forProvider:
    region: us-east-1
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    allocatedStorage: 20
    engine: postgres
    engineVersion: "9.6"
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef:
    namespace: system:default/vnncld-idp
    name: system:default/vnncld-idp-dev-db