---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paulao
resources:
  - namespace.yaml
  - paulao-quota.yaml
  - paulao-deployment.yaml
  - paulao-service.yaml
  - paulao-vs.yaml
  - paulao-hpa.yaml