resources:
  - kind: v1/namespaces
    selector:
      query: .metadata.name | contains("kube-system")
    port:
      entity:
        mappings:
          - identifier: '"vnncld"'
            title: '"vnncld"'
            blueprint: '"cluster"'
            
  - kind: v1/namespaces
    selector:
      query: .metadata.environment == "true"
    port:
      entity:
        mappings:
          - identifier: .metadata.name + "-" + "vnncld"
            title: .metadata.labels.environment
            blueprint: '"environment"'
            relations:
              cluster: '"vnncld"'

  - kind: v1/namespaces
    selector:
      query: .metadata.name | startswith("kube") | not
    port:
      entity:
        mappings:
          - identifier: .metadata.name + "-" + "vnncld"
            title: .metadata.name
            blueprint: '"namespace"'
            properties:
              creationTimestamp: .metadata.creationTimestamp
              labels: .metadata.labels
            relations:
              Cluster: '"vnncld"'

  - kind: v1/nodes
    port:
      entity:
        mappings:
          - identifier: (.metadata.name) | (split(".")|join("_")) + "-" + "vnncld"
            title: .metadata.name + "-" + "vnncld"
            icon: '"Node"'
            blueprint: '"node"'
            properties:
              creationTimestamp: .metadata.creationTimestamp
              totalCPU: .status.allocatable.cpu
              totalMemory: .status.allocatable.memory
              labels: .metadata.labels
              kubeletVersion: .status.nodeInfo.kubeletVersion | split("-") | .[0]
              ready: .status.conditions[] | select(.type == "Ready") | .status
            relations:
              Cluster: '"vnncld"'

  - kind: v1/pods
    selector:
      query: .metadata.namespace | startswith("kube") | not 
    port:
      entity:
        mappings:
          - identifier: .metadata.name + "-" + .metadata.namespace + "-" + "vnncld"
            title: .metadata.name
            icon: '"Microservices"'
            blueprint: '"pod"'
            properties:
              startTime: .status.startTime
              phase: .status.phase
              labels: .metadata.labels
              containers: (.spec.containers | map({image, resources})) + .status.containerStatuses | group_by(.image) | map(add)
              conditions: .status.conditions
            relations:
              Node: (.spec.nodeName) | (split(".")|join("_")) + "-" + "vnncld"
