apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: order.pauloponciano.pro
spec: 
  compositeTypeRef:
    apiVersion: api.pauloponciano.pro/v1alpha1
    kind: XCustomOrder
  patchSets:
    - name: common-fields
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
  resources:
## API GATEWAY
    - name: order-api-gateway
      base:
        apiVersion: apigateway.aws.upbound.io/v1beta1
        kind: RestAPI
        metadata:
          name: order-api
          labels:
            app.kubernetes.io/created-by: crossplane
            type: api-order
        spec: 
          forProvider:
            name: order-api-gateway
            region: to-be-patched
      patches:
        - type: PatchSet
          patchSetName: common-fields 
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.tags
          toFieldPath: spec.forProvider.tags
          policy:
            mergeOptions:
              keepMapValues: true
    - name: order-api-gateway-resource
      base:
        apiVersion: apigateway.aws.upbound.io/v1beta1
        kind: Resource
        metadata:
          name: order-api-resource
          labels:
            app.kubernetes.io/created-by: crossplane
            type: order-resource
        spec: 
          forProvider:
            region: to-be-patched
            pathPart: order
            matchControllerRef: true
            parentIdSelector:
              matchLabels:
                type: api-order
            restApiIdSelector:
              matchLabels:
                type: api-order
      patches:
        - type: PatchSet
          patchSetName: common-fields
    - name: order-api-method-post
      base:
        apiVersion: apigateway.aws.upbound.io/v1beta1
        kind: Method
        metadata:
          name: order-api-method-post
          labels:
            app.kubernetes.io/created-by: crossplane
            type: api-order-method-post
        spec: 
          forProvider:
            region: to-be-patched
            httpMethod: POST
            authorization: NONE
            matchControllerRef: true
            restApiIdSelector:
              matchLabels:
                type: api-order
            resourceIdSelector:
              matchLabels: 
                type: order-resource
      patches:
        - type: PatchSet
          patchSetName: common-fields
    - name: api-order-lambda-integration
      base:
        apiVersion: apigateway.aws.upbound.io/v1beta1
        kind: Integration
        metadata:
          name: api-order-lambda-integration
          labels:
            app.kubernetes.io/created-by: crossplane
            type: api-order-lambda-integration
        spec: 
          forProvider:
            region: to-be-patched
            type: AWS_PROXY
            matchControllerRef: true
            restApiIdSelector:
              matchLabels:
                type: api-order
            uriSelector:
              matchLabels:
                type: lambda-order
            integrationHttpMethod: POST
            resourceIdSelector:
              matchLabels:
                type: order-resource
            httpMethodSelector:
              matchLabels: 
                type: api-order-method-post        
      patches:
        - type: PatchSet
          patchSetName: common-fields
    - name: api-order-deployment
      base:
        apiVersion: apigateway.aws.upbound.io/v1beta1
        kind: Deployment
        metadata:
          name: api-order-deployment
          labels:
            app.kubernetes.io/created-by: crossplane
            type: api-order-deployment
        spec: 
          forProvider:
            region: to-be-patched
            matchControllerRef: true
            restApiIdSelector:
              matchLabels:
                type: api-order
            stageName: Stage
            stageDescription: Non-Production                
      patches:
        - type: PatchSet
          patchSetName: common-fields
## LAMBDA IAM
    - name: lambda-order-custom-policy
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: Policy
        metadata:
          name: lambda-order-custom-policy
          labels:
            type: lambda-order-custom-policy
        spec:
          forProvider:
            policy: |
              {
                "Version": "2012-10-17",
                "Statement": [
                  {
                      "Effect": "Allow",
                      "Action": [
                          "logs:CreateLogGroup",
                          "logs:CreateLogStream",
                          "logs:PutLogEvents",
                          "xray:PutTraceSegments",
                          "xray:PutTelemetryRecords",
                          "events:PutEvents",
                          "s3:GetObject"
                      ],
                      "Resource": "*"
                  }
                ]
              }
      patches:
        - type: PatchSet
          patchSetName: common-fields
    - name: function-role
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: Role
        metadata:
          name: lambda-order-role
          labels:
            app.kubernetes.io/created-by: crossplane
            type: lambda-order-role
        spec:
          forProvider:
            assumeRolePolicy: |
              {
                "Version": "2012-10-17",
                "Statement": [
                  {
                    "Effect": "Allow",
                    "Principal": {
                      "Service": "lambda.amazonaws.com"
                    },
                    "Action": "sts:AssumeRole"
                  }
                ]
              }
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-role"
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.functionRoleArn
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.functionRoleName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.permissionsBoundaryArn
          toFieldPath: spec.forProvider.permissionsBoundary
    - name: lambda-basic-policy-attachment
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: RolePolicyAttachment
        spec:
          forProvider:
            #policyArn: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            policyArnSelector:
              matchLabels:
                type: lambda-order-custom-policy
            roleSelector:
              matchControllerRef: true
              matchLabels:
                type: lambda-order-role
      patches:
        - type: PatchSet
          patchSetName: common-fields
## LAMBDA FUNCTION
    - name: lambda-order
      base:
        apiVersion: lambda.aws.upbound.io/v1beta1
        kind: Function
        metadata:
          name: lambda-order
          annotations:
            meta.upbound.io/example-id: lambda/v1beta1/function
            uptest.upbound.io/timeout: "3600"
          labels:
            type: lambda-order
        spec:
          forProvider:
            handler: handler.js
            packageType: Zip
            region: to-be-patched
            matchControllerRef: true
            roleSelector:
              matchLabels:
                type: lambda-order-role
            runtime: nodejs14.x
            s3Bucket: pauloponciano-lambda-order
            s3Key: lambda_order.zip
            timeout: 60
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.functionName
        - type: FromCompositeFieldPath
          fromFieldPath: status.functionRoleArn
          toFieldPath: spec.forProvider.role
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.functionArn
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.functionName