apiVersion: api.pauloponciano.pro/v1alpha1
kind: XCustomOrder
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"api.pauloponciano.pro/v1alpha1","kind":"CustomOrder","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"aws-serverless-stack"},"name":"order-composition","namespace":"default"},"spec":{"resourceConfig":{"providerConfigName":"default","region":"us-east-1","tags":{"ownerName":"SRE","projectName":"PE"}}}}
  finalizers:
    - composite.apiextensions.crossplane.io
  generateName: order-composition-
  generation: 5
  labels:
    app.kubernetes.io/instance: aws-serverless-stack
    crossplane.io/claim-name: order-composition
    crossplane.io/claim-namespace: default
    crossplane.io/composite: order-composition-qmfjw
  managedFields:
    - apiVersion: api.pauloponciano.pro/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:functionArn': {}
      manager: Go-http-client
      operation: Update
      subresource: status
      time: '2023-10-06T18:25:51Z'
    - apiVersion: api.pauloponciano.pro/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:finalizers':
            .: {}
            'v:"composite.apiextensions.crossplane.io"': {}
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:crossplane.io/claim-name': {}
            'f:crossplane.io/claim-namespace': {}
            'f:crossplane.io/composite': {}
        'f:spec':
          .: {}
          'f:claimRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
          'f:compositionRef':
            .: {}
            'f:name': {}
          'f:compositionRevisionRef':
            .: {}
            'f:name': {}
          'f:compositionUpdatePolicy': {}
          'f:resourceConfig':
            .: {}
            'f:providerConfigName': {}
            'f:region': {}
            'f:tags':
              .: {}
              'f:ownerName': {}
              'f:projectName': {}
          'f:resourceRefs': {}
      manager: Go-http-client
      operation: Update
      time: '2023-10-06T19:36:25Z'
  name: order-composition-qmfjw
  resourceVersion: '50220'
  uid: 7d84e96b-9c5c-410b-81b3-02f493e4af9e
spec:
  claimRef:
    apiVersion: api.pauloponciano.pro/v1alpha1
    kind: CustomOrder
    name: order-composition
    namespace: default
  compositionRef:
    name: order.pauloponciano.pro
  compositionRevisionRef:
    name: order.pauloponciano.pro-4d44fc1
  compositionUpdatePolicy: Automatic
  resourceConfig:
    providerConfigName: default
    region: us-east-1
    tags:
      ownerName: SRE
      projectName: PE
  resourceRefs:
    - apiVersion: apigateway.aws.upbound.io/v1beta1
      kind: RestAPI
      name: order-composition-qmfjw-c98sz
    - apiVersion: apigateway.aws.upbound.io/v1beta1
      kind: Resource
      name: order-composition-qmfjw-tp8nf
    - apiVersion: apigateway.aws.upbound.io/v1beta1
      kind: Method
      name: order-composition-qmfjw-gbbs5
    - apiVersion: apigateway.aws.upbound.io/v1beta1
      kind: Integration
      name: order-composition-qmfjw-djkv8
    - apiVersion: apigateway.aws.upbound.io/v1beta1
      kind: Deployment
      name: order-composition-qmfjw-k9p95
    - apiVersion: iam.aws.upbound.io/v1beta1
      kind: Policy
      name: order-composition-qmfjw-h6h98
    - apiVersion: iam.aws.upbound.io/v1beta1
      kind: Role
      name: order-composition-qmfjw-role
    - apiVersion: iam.aws.upbound.io/v1beta1
      kind: RolePolicyAttachment
      name: order-composition-qmfjw-zwd4b
    - apiVersion: lambda.aws.upbound.io/v1beta1
      kind: Function
      name: order-composition-qmfjw-9vkzl
    - apiVersion: lambda.aws.upbound.io/v1beta1
      kind: Function
      name: order-composition-qmfjw-ssb2w
    - apiVersion: lambda.aws.upbound.io/v1beta1
      kind: Permission
      name: order-composition-qmfjw-j8rzh
    - apiVersion: lambda.aws.upbound.io/v1beta1
      kind: Permission
      name: order-composition-qmfjw-brjn9
    - apiVersion: cloudwatchevents.aws.upbound.io/v1beta1
      kind: Rule
      name: order-composition-qmfjw-plrs9
    - apiVersion: cloudwatchevents.aws.upbound.io/v1beta1
      kind: Target
      name: order-composition-qmfjw-fxql2
status:
  conditions:
    - lastTransitionTime: '2023-10-06T18:20:50Z'
      reason: ReconcileSuccess
      status: 'True'
      type: Synced
    - lastTransitionTime: '2023-10-06T18:25:51Z'
      reason: Available
      status: 'True'
      type: Ready
  functionArn: 'arn:aws:lambda:us-east-1:310240692520:function:order-composition-qmfjw-ssb2w'