apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: crossplane-igw
  annotations:
    argocd.argoproj.io/tracking-id: application:apps/Deployment:default/resource-deployment
spec:
  forProvider:
    region: us-east-2
    tags:
      Name: crossplane-igw
      Owner: SRE
      Project: PE
    vpcIdSelector:
      matchLabels: 
        env: network-aws-vpc-1
