---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  name: eip-ngw
  annotations:
    argocd.argoproj.io/tracking-id: application:apps/Deployment:default/resource-deployment
spec:
  forProvider:
    region: us-east-2
    vpc: true
    tags:
      Name: eip-ngw
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: crossplane-ngw
  annotations:
    argocd.argoproj.io/tracking-id: application:apps/Deployment:default/resource-deployment
spec:
  forProvider:
    region: us-east-2
    connectivityType: public
    allocationIdRef:
      name: eip-ngw
    subnetIdRef:
      name: subnet-public1-crossplane-us-east-2a
    tags:
      Name: crossplane-ngw
  providerConfigRef:
    name: default