apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: rtb-crossplane-private
  annotations:
    argocd.argoproj.io/tracking-id: application:apps/Deployment:default/resource-deployment
spec:
  forProvider:
    region: us-east-2
    tags:
      Name: rtb-crossplane-private
    vpcIdSelector:
      matchLabels: 
        env: network-aws-vpc-1
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: rta-crossplane-private-2a
  annotations:
    argocd.argoproj.io/tracking-id: application:apps/Deployment:default/resource-deployment
spec:
  forProvider:
    region: us-east-2
    routeTableIdRef:
      name: rtb-crossplane-private
    subnetIdRef:
      name: subnet-private1-crossplane-us-east-2a
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: rta-crossplane-private-2b
  annotations:
    argocd.argoproj.io/tracking-id: application:apps/Deployment:default/resource-deployment
spec:
  forProvider:
    region: us-east-2
    routeTableIdRef:
      name: rtb-crossplane-private
    subnetIdRef:
      name: subnet-private2-crossplane-us-east-2b
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: route-private
  annotations:
    argocd.argoproj.io/tracking-id: application:apps/Deployment:default/resource-deployment
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    natGatewayIdRef:
      name: crossplane-ngw
    region: us-east-2
    routeTableIdRef:
      name: rtb-crossplane-private





