apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: crossplane-vpc
  annotations:
    argocd.argoproj.io/tracking-id: application:apps/Deployment:default/resource-deployment
  labels:
    env: network-aws-vpc-1
spec:
  forProvider:
    region: us-east-2
    cidrBlock: 10.10.0.0/16
    instanceTenancy: default
    enableDnsHostnames: true
    enableDnsSupport: true
    tags:
      Name: crossplane-vpc
      Owner: SRE
      Project: PE
  providerConfigRef:
    name: irsa-providerconfig
    kind: ProviderConfig
