# CLAIM
---
apiVersion: api.pauloponciano.pro/v1alpha1
kind: CustomDatabase
metadata:
  name: -dev-db
  namespace: environment-crossplane
spec:
  resourceConfig:
    providerConfigName: aws
    region: 
    size: 
    engine: 
    version: 
    tags:
      automation-by: crossplane
      ownerName: group:default/sre

