---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paulao-3
resources:
  - namespace.yaml
  - paulao-3-quota.yaml
  - paulao-3-deployment.yaml
  - paulao-3-service.yaml
  - paulao-3-vs.yaml
  - paulao-3-hpa.yaml