---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: paulao-3-quota
  namespace: paulao-3
  labels:
    kubernetes.io/metadata.name: paulao-3
    backstage.io/kubernetes-id: paulao-3
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi